### ISSUE TITLE
Generated GUIDs don't appear to be UUID v4 conformant

### ISSUE THREAD

**Issue by CrookedNumber** [APMG/pmp-sdk-perl#2]
E.g. - 25c262f1-b29a-5d82-5dd0-3b29c9f5113c

**Comment by pkarman** [comment]
This is not a problem with the Perl SDK. The Perl SDK uses UUID v4 module:
https://github.com/APMG/pmp-sdk-perl/blob/master/lib/Net/PMP/CollectionDoc.pm#L297

I think you are seeing invalid v4 UUIDs because APM intentionally abuses the UUID pattern with its own internal GUIDs, which are not UUIDs but md5 checksums.
